name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    go_router: ^17.0.1
    intl: ^0.19.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/on_boarding_background.png
        - assets/images/home_background.png
        - assets/images/easytransfert_logo.png
        - assets/images/operators/mtn_logo.png
        - assets/images/operators/orange_logo.png
        - assets/images/operators/wave_logo.png
        - assets/images/operators/moov_logo.png
        - assets/fonts/

    fonts:
        - family: Outfit
          fonts:
              - asset: assets/fonts/outfit/Outfit-Regular.ttf
                weight: 400
              - asset: assets/fonts/outfit/Outfit-Medium.ttf
                weight: 500
              - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/outfit/Outfit-Bold.ttf
                weight: 700
              - asset: assets/fonts/outfit/Outfit-Black.ttf
                weight: 900

        - family: Poppins
          fonts:
              - asset: assets/fonts/poppins/Poppins-Regular.ttf
                weight: 400
              - asset: assets/fonts/poppins/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/poppins/Poppins-Bold.ttf
                weight: 700
              - asset: assets/fonts/poppins/Poppins-Black.ttf
                weight: 900
